### PR TITLE
fix Memory leak

### PR DESCRIPTION
**Pull request by mcoo**

### CODE REVIEW

**Comment by mcoo** [comment]
#10

**Comment by vertex-admin** [comment]
I would like to confirm this memory leak as well, but I can't pinpoint where it's coming from. Any ideas?

**Comment by mcoo** [comment]
https://github.com/psykhi/wordclouds/blob/master/wordcloud.go#L388
When the Program want to exit, `workCh` is full. So Thread blocking，it cannot receive the stop sign `stopSendingCh`.
https://github.com/psykhi/wordclouds/blob/master/wordcloud.go#L408
When the Program want to exit, `aggCh` don't close, so deadlock
Sorry my English is not well :(

**Comment by psykhi** [comment]
Hey, sorry for not having looked at this earlier! I'll try to look into your PR this week and see if that fixes the memory leaks. Thanks so much for contributing!

**Comment by mcoo** [comment]
Did you find any problems?

**Comment by vertex-admin** [comment]
Bumping to say that I have used @mcoo's solution over the past 2 weeks and have not experienced a crash since.

**Comment by psykhi** [comment]
Thanks for fixing this, sorry for the slow review!

**Pull request merged**
